network/urls.py
from django.urls import path

from . import views

app_name ="core"

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("create", views.createPost, name = "createPost"),
    path("profile/<str:name>", views.profile, name = "profile"),
    path("follow/<str:username>", views.follow, name ="follow"),
    path("unfollow/<str:username>", views.unfollow, name ="unfollow"),
    path("following", views.following, name = "following"),
    path("edit/<int:post_id>", views.editPost, name ="edit"),
    path("like/<int:post_id>", views.like, name = "like")
]

project4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("network.urls")),
]

network/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class User(AbstractUser):
    following = models.ManyToManyField(
    "self", blank=True, related_name="followers", symmetrical=False
    )


class Post(models.Model):
    owner = models.ForeignKey(User, related_name = "owner", on_delete=models.CASCADE)
    text = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return f"{self.text} by {self.owner}"

class Like(models.Model):
    liker = models.ForeignKey(User, related_name = "liker", on_delete = models.CASCADE)
    liked = models.ManyToManyField(Post, related_name = "likedPosts")

    def __str__(self):
        return f"{self.liker} likes"

class Following(models.Model):
    follower = models.ForeignKey(User, related_name = "fllwer", on_delete= models.CASCADE)
    following = models.ManyToManyField(User, related_name = "followed")

    def __str__(self):
        return f"{self.follower} followings"

network/views.py
from django.db import IntegrityError
from django.core import serializers
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.urls import reverse
from django.contrib. auth import authenticate, login, logout
from django.core.paginator import Paginator
from django.views.decorators.csrf import csrf_exempt

from .models import *

import json

def index(request):
    currentUser = request.user

    if not Like.objects.filter(liker= currentUser).exists():    
        f= Like(liker = currentUser)
        f.save()
    likedList = Like.objects.get(liker = currentUser)
    likedList = likedList.liked.all()

    posts = Post.objects.all().order_by("-timestamp")
    paginator = Paginator(posts, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {"posts": page_obj, "likes":likedList, }
    return render(request, "network/index.html", context)


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("core:index"))
        else:
            return render(request, "network/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "network/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("core:index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "network/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "network/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("core:index"))
    else:
        return render(request, "network/register.html")

def createPost(request):
    if request.method == "POST":
        text = request.POST.get("post-text")
        owner = request.user
        f = Post(text = text, owner = owner )
        f.save()
        return HttpResponseRedirect(reverse("core:index"))

def profile(request, name):
    user = User.objects.get(username = name)

    currentUser = request.user

    if not Following.objects.filter(follower = user).exists():
        f = Following(follower = currentUser)
        f.save()

    followings = Following.objects.get(follower = currentUser)
    just = Following.objects.get(follower = user)
    print(user.followed.all())
    isFollowed = user in followings.following.all()
    context = {"profile": user, "isFollowed":isFollowed, "name":user.username, "following": Following.objects.get(follower = user)}
    return render(request,"network/profile.html", context)

def follow(request, name):
    user = User.objects.filter(username = name).values()
    if request.method == "PUT":
        return JsonResponse(user, safe = False)
        
def api_current_user(request):
    user = list(User.objects.filter(pk=request.user.pk).values(
        "username"
    ))
    return JsonResponse(user, safe = False)

def follow(request, username):
    prof = User.objects.get(username = username)
    if request.method == "POST":
        if Following.objects.filter(follower = request.user).exists():
            user = Following.objects.get(follower = request.user)
            user.following.add(User.objects.get(username = username))
        else:
            f = Following(follower = request.user)
            f.save()
        return HttpResponseRedirect(reverse(f"core:profile", kwargs = {"name": prof.username}))    
    else:
        return HttpResponse("error")

def unfollow(request, username):
    prof = User.objects.get(username = username)
    if request.method == "POST":
        if Following.objects.filter(follower = request.user).exists():
            user = Following.objects.get(follower = request.user)
            user.following.remove(User.objects.get(username = username))
        else:
            f = Following(follower = request.user)
            f.save()
        return HttpResponseRedirect(reverse(f"core:profile", kwargs = {"name": prof.username}))    
    else:
        return HttpResponse("error")

def following(request):
    user = Following.objects.get(follower = request.user)
    posts= Post.objects.filter(owner__in=user.following).order_by('-timestamp') # showing followed user's posts
    context = {"posts":posts,"following":user}
    return render(request, "network/following.html", context)

@csrf_exempt
def editPost(request, post_id):
    post = Post.objects.filter(id = post_id)
    data = request.body.decode('utf-8')
    json_data = json.loads(data)
    if request.method =="POST":
        editedText = json_data.get("editedText", "")
        post.update(text=  editedText)
        return JsonResponse({"status":"edited successfully"})
    else:
        return JsonResponse({"error":"400"}, status = 400)

@csrf_exempt
def like(request, post_id):
    if not Like.objects.filter(liker = request.user).exists():
        f = Like(liker = user)
        f.save()
    data = request.body.decode('utf-8')
    # it takes request.user and relevant post and creates new Like model( user = request.user, post = post)
    post = Post.objects.get(id = post_id)
    user = request.user
    user_likes = Like.objects.get(liker = user)
    if request.method == "POST":
        if Like.objects.filter(liker = user).exists() and post in user_likes.liked.all():
            like = Like.objects.get(liker = user)
            like.liked.remove(post)
            return JsonResponse({"like":False})
        elif not post in user_likes.liked.all():
            like = Like.objects.get(liker = user)
            like.liked.add(post)
            return JsonResponse({"like":True})
    return JsonResponse({"error":"wrong method! Should be PUT"})

network/templates/network/following.html
{% extends "network/layout.html" %}

{% block body %}
<h1>All posts</h1>

{% if request.user.is_authenticated %}
<ul class="list-group list-group-flush">
<li class="list-group-item">
    <form action="{% url 'core:createPost' %}" method = "POST" >
    {% csrf_token %}
    <div class="form-group">
      <label for="post-text">Create Post</label>
      <input type="text" class="form-control" name = "post-text" id="post-text" placeholder="text to your post">
    </div>
    <button type="submit" class="btn btn-primary">Post</button>
</form></li>

</ul>
{% endif %}
{% for post in posts %}
<div class="border border-secondary post">
<div class="list-group">
    <div class="d-flex w-100 justify-content-between">
      <h5 class="mb-1">Posted by: <a href = "{% url 'core:profile' post.owner%}">{{post.owner}}</a></h5>
      <small class="text-muted">{{post.timestamp}}</small>
    </div>
    <p class="mb-1">{{post.text}}</p>
    <span class = "d-flex"><button type="button" class="btn btn-outline-danger"><i  class="bi bi-balloon-heart">Like</i></button></span>{% if post.owner == request.user %} <a href = "#">Edit</a>{% endif %}
</div>
</div>
{% endfor %}

{% endblock %}

network/templates/network/index.html
{% extends "network/layout.html" %}

{% block body %}
<h1>All posts</h1>
{% if request.user.is_authenticated %}
<ul class="list-group list-group-flush">
<li class="list-group-item">
    <form action="{% url 'core:createPost' %}" method = "POST" >
    {% csrf_token %}
    <div class="form-group">
      <label for="post-text">Create Post</label>
      <input type="text" class="form-control" name = "post-text" id="post-text" placeholder="text to your post">
    </div>
    <button type="submit" class="btn btn-primary">Post</button>
</form></li>

</ul>
{% endif %}
{% for post in posts %}
<div class="border border-secondary post">
  <div class="list-group" id = "{{post.id}}">
      <div class="d-flex w-100 justify-content-between">
        <h5 class="mb-1">Posted by: <a href = "{% url 'core:profile' post.owner%}">{{post.owner}}</a></h5>
        <small class="text-muted">{{post.timestamp}}</small>
      </div>
      <p class="mb-1" id = "post-text">{{post.text}}</p>
    <span class = "d-flex"><button type="button" class="btn btn-outline-danger" id ="like">{% if post in likes%}<i  class="bi bi-balloon-heart">Unlike</i>{%else%}<i  class="bi bi-balloon-heart">Like</i>{% endif %}</button></span>
    {% if request.user == post.owner %}
    <span class = "d-flex"><button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" id = "edit">
      Edit
      </button></span>
    {% endif %}
    </div>

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="form-group edit-post-form">
  
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal" id = "close">Close</button>
        <button type="submit" class="btn btn-primary " id = "save">Save changes</button>
      </div>
    </div>
  </div>
</div>
</div>
{% endfor %}
<nav aria-label="Page navigation example">
  <ul class="pagination">
    {% if posts.has_previous %}
    <li class="page-item"><a class ="page-link" href="?page={{ posts.previous_page_number }}">previous</a></li>
    {% endif %}
    {% if posts.has_next %}
    <li class="page-item"><a href="?page={{ posts.next_page_number }}" class = "page-link">next</a></li>
    {% endif %}
  </ul>
  {% comment %} <script>

    const button = document.querySelector("#edit");

    button.addEventListener('click', function(event){
        let post = event.target.parentElement.closest('div'); 
        fetch(`edit/${post.id}`, {
          method: 'POST',
          body: JSON.stringify({
            ///
          })
        });
    });
  </script> {% endcomment %}
{% endblock %}

network/templates/network/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Social Network{% endblock %}</title>
        
        <script src="{% static 'network/js/awesome-fonts.js' %}" crossorigin="anonymous"></script>

        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'network/css/styles.css' %}" rel="stylesheet">
    </head>
    <body>

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'core:index' %}">Network</a>
          
            <div>
              <ul class="navbar-nav mr-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'core:profile'  user.username%}"><strong id = "username">{{ user.username }}</strong></a>
                    </li>
                {% endif %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'core:index' %}">All Posts</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'core:following' %}">Following</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'core:logout' %}">Log Out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'core:login' %}">Log In</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'core:register' %}">Register</a>
                    </li>
                {% endif %}
              </ul>
            </div>
          </nav>
        
        <div class="body">
            {% block body %}
            {% endblock %}
        </div>
         
        <script src = "{% static 'network/js/index.js' %}"></script>


    </body>
</html>

network/templates/network/login.html
{% extends "network/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'core:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'core:register' %}">Register here.</a>

{% endblock %}

network/templates/network/profile.html
{% extends 'network/layout.html' %}
{% load static %}


{% block body %}
<div>
    <h2>Profile of {{profile.username}}</h2>
    <div class ="main-profile">
        <div class = "info">
            <p>
                <img class = "round-photo"src="{% static 'network/img/41e8311543aba9491257f4d6f455322d.jpeg' %}" alt="" rounded-corners >
                <div class = "form-group">
                    <div>
                        {{following.follower.count}}
                        
                        <ul class="list-group">
                        <li class="list-group-item active" aria-current="true">More info</li>
                        <li class="list-group-item" id = "profile_username">Name: {{profile.username}}</li>
                        <li class="list-group-item">Followers: {{profile.followed.count}}</li>
                        <li class="list-group-item">Following: {{following.following.count}}</li>
                        {% if request.user.is_authenticated %}
                            {% if isFollowed %}
                            <div class ="form-group">
                                <form action="{% url 'core:unfollow' profile.username%}"  method = "POST">
                                    {% csrf_token %}
                                    <button class ="btn btn-danger" id = "follow">Unfollow</button>
                                </form>
                            </div>
                            {% else %}
                            <div class ="form-group">
                                <form action="{% url 'core:follow' profile.username%}" method = "POST">
                                    {% csrf_token %}
                                    <button class ="btn btn-success" id = "follow">Follow</button>
                                </form>
                            </div>
                            {% endif %}
                        {% endif %}
                      </ul>
                    </div>
                </div>
            </p>
        </div>

    </div>


</div>
<script>

    

</script>
{% endblock body %}

network/templates/network/register.html
{% extends "network/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'core:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'core:login' %}">Log In here.</a>

{% endblock %}